//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Учёт_склада
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leaves
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
